### ISSUE TITLE
How should ZoneMinder be set for your scripts to work with it as a timelapse?

### ISSUE THREAD

**Issue by Number6UK** [rakhbari/zm-archiver#1]
Hi,
This looks perfect for a timelapse project I want to do.
I already have ZoneMinder (and ffmpeg) installed and running as a motion detector and this is working well.
For the motion detection setup I have, I have a ZM monitor of Function type "Modetect".

In addition to those motion-detected videos, I would like to have a timelapse covering, e.g. each 24-hour or each 1-week period.
In order to do this, do I need to add a new monitor in ZM and if so, what would the basic settings of that ZM monitor be?
e.g. should the Function be "Monitor", "Mocord", "Record", etc.? Do I need to change "Captures per frame"?

It would be extremely helpful if you could outline what needs to be done (and why) on the ZM side to allow your very useful scripts to work.

Thanks!

**Comment by rakhbari** [comment]
Just from your 1st question I feel perhaps my README isn't as clear as it needs to be. So here's some clarifications...

This ZM archiver project has very low coupling to ZM itself. In fact, ZM doesn't even need to be installed on the host where you run `zm-archiver` scripts. The only dependency on the archiver and ZM is the directory structure that ZM creates while it's recording events.

There are 2 phases to `zm-archiver`: 1) `prep-jpegs.sh` and 2) `make-mpg.sh`

The only dependency that `prep-jpegs.sh` has on ZM is where the root of the ZM events directory lives, set by `zm_events_path` (a variable set at the top of that script). And of course, it also depends on the directory structure that ZM creates under that path.

With all that said, the answer to your first question is... No, you don't need any additional monitor definitions in ZM to use `prep-jpegs.sh`. That's actually a big advantage of `zm-archiver` over other time-lapse mechanisms I've seen around the web.

You simply record your events as per normal using ZM's standard `Modect` or `Mocord` triggers. In fact `prep-jpegs.sh` doesn't even care how you ended up with the event directory structure under `zm_events_path`. As long as the ZM created directory structure exists under `zm_events_path`, it'll blissfully just work!

However my recommendation for a decent frame rate for any of your camera feeds is 5 FPS. And just to be clear, you set the FPS rate at the camera, not in ZM. For whatever reason I've never been able to get ZM to make stable recordings when I try to set the `Maximum FPS` setting under monitor configuration. So what I do is set the FPS on my camera streams so that way I leave `Maximum FPS` blank in ZM.

Other than this you don't need anything else. Simply check to make sure that the `zm_events_path` variable in `prep-jpegs.sh` is pointing to a real path on whichever host you're running it on. Then...

1. Run `prep-jpegs.sh` to prepare the jpegs into a single file ready for the 2nd script.
2. Run `make-mpg.sh` to use the output of `prep-jpegs.sh` and create your MPEG video. 

Whether or not you end up with a time-lapse MPEG video is completely up to you. You end up with a time-lapse *IF* you define the `<frames-to-skip>` value to anything above 0 in your spec file. This part is well explained in the README.

Hopefully this makes it a lot more clear for you. Let me know if you still need any guidance.
